safe:        false
auto:        true
server:      true
server_port: 4000
baseurl:     /
url:         http://localhost:4000

future:      true
markdown:    rdiscount
permalink:   /:title

rdiscount:
  extensions: []